### PR TITLE
added feature to visualize intensity/rgb color in pcd ASCII/BINARY files

### PR DESCRIPTION
**Pull request by Gekk0r**
Based on @MacBlub modification,

Upgraded version that allows to load RGB data in PCD Binary files.

### CODE REVIEW

**Comment by dmandrioli** [comment]
Hi Daniele, thanks for your contribution! 
Could you provide some sample PCD files to facilitate the review?

**Comment by Gekk0r** [comment]
Sure!
I used PCL 1.8 to convert a ply in a binary pcd.
In this example, I used a result of processing from slam data downloaded in this website (https://www.eth3d.net/datasets). Obviously, you can use your data in the same way ;).

Let me know if you need more details :)

ETH facade dataset : https://gofile.io/?c=9p4nCD

**Comment by dmandrioli** [comment]
Hi, great work. Displaying RGB data works very well with the provided ETH pcd. 
I also tried to display intensity using default sample pcd file which already includes an intensity column but the current Map2Color implementation just draws everything in red, which is expected without a dedicated color mapping.

I'm wondering why you support RGB only in binary PCD and intensity only in ASCII pcd?

I suggest to support RGB as-is for both ascii and binary formats and drop the intensity color mapping feature. It would be up to the user to preprocess intensity data as needed to leverage the RGB feature. What do you think about this?

**Comment by Gekk0r** [comment]
> I'm wondering why you support RGB only in binary PCD and intensity only in ASCII pcd?
This is only a starting point :), there is a long list of features that I want add to your project...

In my TODO, I have planned to integrate RGB in ascii, binary and binary compressed then export everything in pcd ascii.

I will let you know my next updates ;)

**Comment by dmandrioli** [comment]
>This is only a starting point :), there is a long list of features that I want add to your project...

Nice :)

I would like to leverage your RGB feature, I will implement my suggestion right now as an extra commit to this pull request to let you give feedback. Supporting all formats should be "free" just by removing these kind of conditions ` if (this.compression === 'binary')`

**Comment by Gekk0r** [comment]
Awesome ;)

**Comment by dmandrioli** [comment]
Daniele, You can check [this branch](https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor/commits/pull/78) which is based on your PR.

If a rgb field is available, the light bulb toggle button is available.

**Pull request merged**
