### PR TITLE
dockerfile support

### PR DESCRIPTION
**Pull request by BlurryLight**
For the sake of docker images, a docker file and corresponding conf is provided.

### CODE REVIEW

**Comment by dmandrioli** [comment]
Thanks for contributing. Can you please provide instructions to run it with docker, especially how to map folders and set up settings.json?

**Comment by BlurryLight** [comment]
AFAIK, the project provided a docker image which was in a very old version. The dockerfile is similar as the way you built the old image, accroding to the https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor/issues/20. Therefore the docker image should behaves similarly as he old one.

On a recent commit, the chapter about docker was removed from the README.md. This PR is aimed at bringing that back.
https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor/commit/eba8160a60cb5acf4f5a7eefb198671f4031dceb

I have built the latest image in [blurrylight/semantic-segmentation-editor](https://hub.docker.com/r/blurrylight/semantic-segmentation-editor).
And the correct way to run it is 
```
docker run -p <PORT>:3000 -e METEOR_SETTINGS="$(cat <PATH_TO_settings.json>)" -v <INPUT_FOLDER>:/home/node/sse-images -v <OUTPUT_FOLDER>:/home/node/sse-internal blurrylight/semantic-segmentation-editor:latest
```
The `<PORT>`, `<PATH_TO_settings.json>`,`<INPUT_FOLDER>`,`<OUTPUT_FOLDER>` should be replaced by users.

**Comment by dmandrioli** [comment]
Ok thanks. Launchpad is pretty old and not maintained, moreover it's pretty heavy to use that's why I'd preferred to remove it from the project. There are new alternatives like https://github.com/disney/meteor-base that I would like to investigate.

**Comment by BlurryLight** [comment]
That's great.  The Launchpad allows me to run it in docker instead of compiling it everytime I run it. That's enough for me. 
But I hope there will be images provided *officially*. You can link the project to dockerhub, with a dockerfile, the dockerhub CI will automatially build a docker image when commits are pushed to github.

**Comment by dmandrioli** [comment]
>But I hope there will be images provided officially. You can link the project to dockerhub, with a dockerfile, the dockerhub CI will automatially build a docker image when commits are pushed to github

I fully agree, let's move into this direction.

**Comment by dmandrioli** [comment]
Fixed in v1.5.0

**Comment by BlurryLight** [comment]
@dmandrioli  Will it be better to let dockerhub bot to compile the image and therefore allow users to pull image from dockerhub rather than compose the image on their own machines? Just link the dockerhub bot to your projects and it will trigger a new building task once a commit is pushed.

**Comment by dmandrioli** [comment]
Hi, thanks for your feedback.
The dockerhub bot actually build the image using the Dockerfile 
 from https://github.com/disney/meteor-base which relies on Docker Compose to run the app wired to a Mongo container. It does not prevent users to pull image from dockerhub. Could you explain why it is a limitation for you to use Docker Compose to run the app? Thanks.

**Comment by BlurryLight** [comment]
well, I have never used 'docker compose' before and I have few idea about it. All my knowledge about docker is "pull a nice image from dockerhub and run it". XD
I will have a try on the latest release and thanks for your great work.

**Pull request closed without merging**
